### PR TITLE
Nova 4 Update

### PR DESCRIPTION
**Pull request by the-alichemist**

### CODE REVIEW

**Comment by WillyReyno** [comment]
The following error occurs on fresh nova install because of a missing lodash dependency in `package.json`, blocking the dashboard card's loading.

Capture d’écran 2022-07-29 à 13 23 33

This error is not be triggered if a custom tool is already installing the lodash dependency. 

It seems Nova is no longer providing lodash out of the box : https://github.com/laravel/nova-issues/discussions/3814#discussioncomment-2509234

**Comment by ValentinGaudin** [comment]
Hello, some issue about the CSS, the component can't trigger the dark mode in Nova, stay in light.

Capture d’écran 2022-07-29 à 17 12 50

**Comment by MuzafferDede** [comment]
Sorry guys, i don't have Nova 4 license to work on it. I wish i implemented this package with some tests but unfortunately i didn't. I will try to come back to this package at some point to upgrade.

**Comment by luciantugui** [comment]
I forked this as well for nova 4, I did some styling changed, how do I re-compile? thanks!

**Comment by ValentinGaudin** [comment]
> 

You can add your own style sheet in the NovaServiceProvider 

`    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(): void
    {
        parent::boot();

        Nova::style('white-block', public_path('./style/app.css'));
    }`

**Comment by ValentinGaudin** [comment]
> I forked this as well for nova 4, I did some styling changed, how do I re-compile? thanks!

You can add your own style sheet in the NovaServiceProvider 

```php
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(): void
    {
        parent::boot();

        Nova::style('white-block', public_path('./style/app.css'));
    }
```

**Pull request merged**
